### ISSUE TITLE
Seed and ensuring replicability

### ISSUE THREAD

**Issue by michalovadek** [saudiwin/idealstan#10]
In my experience re-running identical models can yield slightly different results even when `seed` is specified in `id_estimate` (as well as an overall `set.seed`). Has anyone else experienced this as well? Is the behaviour inherent in the Stan code?

Even though the differences are not dramatic, some journals might take issue with results that are not 100% replicable.

**Comment by saudiwin** [comment]
The underlying function to check is `stan` in the `rstan` package for more info about seeds. MCMC is not a deterministic algorithm so there is no expectation that you will get the exact same results until you run it for a considerable number of samples.
