### ISSUE TITLE
Generalized Graded Unfolding Model

### ISSUE THREAD

**Issue by Emily-Chai** [saudiwin/idealstan#14]
Good evening,

Any perspective on implementing generalized graded unfolding model (GGUM; Roberts, Donoghue, & Laughlin, 2000)? Many response data in political science can benefit from fitting that. It would be great to have this model in your package too.

Thanks!

**Comment by saudiwin** [comment]
yes I think this is already implemented, unless i'm wrong. the graded response model I have is generalized (cutpoints vary across items).

**Comment by saudiwin** [comment]
if you can give me some more details I can let you know if the model will work for your data.
