### ISSUE TITLE
Installation problem - rlang?

### ISSUE THREAD

**Issue by MartinsRodrigo** [saudiwin/idealstan#21]
Hi Robert,
Thanks for  updating this excelent package!
I just had an article accepted for publication using your package. Preparing the code for replication, I updated the package and now I'm having problems. It looks like you use the "parse_quosure" function from the rlang package during the installation process, but in newer versions this function no longer exists. I tried installing version 0.4.12 of the rlang package, but some other package you use requires the latest version.

Here is the console output :

```{r}
remotes::install_github('saudiwin/idealstan',build_vignette=TRUE)
Downloading GitHub repo saudiwin/idealstan@HEAD
√  checking for file 'C:\Users\rodri\AppData\Local\Temp\Rtmpkn1eWw\remotes3b644e227126\saudiwin-idealstan-c629bf9/DESCRIPTION' (1.1s)
-  preparing 'idealstan':
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes
         -----------------------------------
-  installing *source* package 'idealstan' ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   Warning: replacing previous import 'bayesplot::rhat' by 'posterior::rhat' when loading 'idealstan'
   Error: 'parse_quosure' is not an exported object from 'namespace:rlang'
   Execution halted
   ERROR: lazy loading failed for package 'idealstan'
-  removing 'C:/Users/rodri/AppData/Local/Temp/RtmpIRCHPJ/Rinst2be467361157/idealstan'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'idealstan' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed
```

Thanks in advance!

**Comment by saudiwin** [comment]
Thanks for debugging this for me. I'll update the code and post a bugfix.

**Comment by ArthurDyevre** [comment]
Hi Robert,

I've been facing the same struggle installing your package:

`devtools::install_github('saudiwin/idealstan',build_vignette=TRUE)'
Downloading GitHub repo saudiwin/idealstan@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: magrittr (2.0.2 -> 2.0.3) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
√  checking for file 'C:\Users\u0090833\AppData\Local\Temp\Rtmpq6ogzc\remotes11b443fe2226\saudiwin-idealstan-c629bf9/DESCRIPTION' (368ms)
-  preparing 'idealstan': (1.2s)
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes
         -----------------------------------
-  installing *source* package 'idealstan' ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   ** inst
   ** byte-compile and prepare package for lazy loading
   Warning: replacing previous import 'bayesplot::rhat' by 'posterior::rhat' when loading 'idealstan'
   Error: object 'parse_quosure' is not exported by 'namespace:rlang'
   Execution halted
   ERROR: lazy loading failed for package 'idealstan'
-  removing 'C:/Users/u0090833/AppData/Local/Temp/RtmpwxiErm/Rinst1d282e855e8c/idealstan'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'idealstan' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed

**Comment by saudiwin** [comment]
OK I'm going to push a new version, though it will have some other new code in it that I've been working on. So if you want to use the beta version with this bug fixed, i'm 
[idealstan-0.99.zip](https://github.com/saudiwin/idealstan/files/8442655/idealstan-0.99.zip)
attaching source code here.

**Comment by saudiwin** [comment]
i.e. from R/Rstudio, you can do 
```
install.packages("idealstan-0.99.zip")
```

**Comment by ArthurDyevre** [comment]
Many thanks! I manage to install locally from the zip file.

Warm wishes,

Arthur

**Comment by MartinsRodrigo** [comment]
Thanks a lot!

**Comment by saudiwin** [comment]
I'm leaving the issue open until a new commit is in the Github master branch.

**Comment by saudiwin** [comment]
This is fixed in develop, so my preference would be to install from develop for now:

```
remotes::install_github("saudiwin/idealstan", ref="develop")
```
