### ISSUE TITLE
  could not find function "run_id"

### ISSUE THREAD

**Issue by jpcoblentz** [saudiwin/idealstan#5]
Any idea what's going on here?

```
ideal_votes <- id_make(score_data = votes_long,
        outcome = "Rank",
        person_id = "voterID",
        item_id = "Candidate",
        high_val = 1,
        low_val = 26,
        miss_val = ""
        )
 
 
 
votes_model <- id_estimate(idealdata= ideal_votes,
                            model_type=3,
                            fixtype='vb',
                            auto_id = F,
                            use_vb=T)
```

Error in run_id(object = object, this_data = this_data, nfix = nfix, restrict_ind_high = restrict_ind_high,  :
  could not find function "run_id"

**Comment by saudiwin** [comment]
Are you using the development version?

**Comment by jpcoblentz** [comment]
I am- it still throws this error: 

```
Error in run_id(object = object, this_data = this_data, nfix = nfix, restrict_ind_high = restrict_ind_high,  : 
  could not find function "run_id"


```

**Comment by saudiwin** [comment]
Please don't use the development version when running models, only if you want to look at code or work on it. If there is a feature you are interested in, just let me know and I can tell you if/when it's implemented.

**Comment by jpcoblentz** [comment]
This error also happens on the non-dev version though

**Comment by saudiwin** [comment]
The only thing wrong in your syntax is that the `auto_id` option no longer exists. If you want me to look more, you'll need to send me some data.

**Comment by jpcoblentz** [comment]
I'll send you some code + data if that works?

**Comment by saudiwin** [comment]
Sure. rmk7@nyu.edu

**Comment by saudiwin** [comment]
So the correct option for `fixtype` is `"vb_full"` not `"vb"`.
