### ISSUE TITLE
Examples contain syntax errors

### ISSUE THREAD

**Issue by zmeers** [saudiwin/idealstan#6]
Hi, 

I'm going through some examples and I noticed that the  `id_estimate()` vignette is broken. Can you please fix various syntax errors in the vignettes? For example, senate_data should be changed to to_idealstan. 

The help page for the function also states that additional arguments can be passed onto the Stan engines. Are they to Stan or to the optional Stan arguments? It's a little unclear...

Otherwise it's an awesome package!

Thanks,
Zoe

**Comment by saudiwin** [comment]
Hi Zoe - 

Thanks for the heads up! Do you mean the "Introduction to Idealstan" vignette? Also are you using the CRAN version or the Github version?

**Comment by zmeers** [comment]
Hi Robert,

Sorry, I should have clarified -- I mean the manual or help page for `id_estimate()` not the vignette. The page that pops up when you type in `??id_estimate`. I'm using the CRAN version. My guess is that Travis and CRAN checks won't catch the problem because it doesn't actually run. I noticed it when I tried to fix a toy example before running my own model. 

Zoe

**Comment by saudiwin** [comment]
I updated the documentation in the latest release (let me know if you find any other errors!)
