### ISSUE TITLE
Function for extracting parameters

### ISSUE THREAD

**Issue by michalovadek** [saudiwin/idealstan#9]
I think a low-hanging feature would be to include a simple(r) function for extracting the estimated parameters (and/or improve documentation). For example, it took me a while to figure out how to access the discrimination parameters (perhaps an oversight on my part), which I do in this rather inelegant way (for a basic logistic model):

`summary(object, pars = "items") %>% 
filter(Predicted Outcome!="Missing", str_detect(Parameter,"reg"))`

I don't know if you are currently overhauling how the internal data frames are set up but if not, then at least a simple wrapper around this code would be helpful. I would suggest just one function, something like `id_extract_param` with argument `param` one of `alpha`, `beta` or `gamma`, because these are the primary quantities of interest for anyone using the model. I would also bring in line the notation in the code with the paper, because it's quite difficult to navigate right now. Perhaps just more documentation overall would help.

**Comment by saudiwin** [comment]
should be fixed in new beta for v1.0
